AFL_TARNAME:=afl-latest
AFL_VERSION:=2.38b
CC:=/afl-$(AFL_VERSION)/afl-gcc
CXX:=/afl-$(AFL_VERSION)/afl-g++
AFL:=/afl-$(AFL_VERSION)/afl-fuzz

.PHONY: clean
clean:
	rm -rf afl-$(AFL_VERSION)

make-afl: unpack-afl
	cd afl-$(AFL_VERSION) && make

unpack-afl:
	tar -zxf $(AFL_TARNAME).tgz

exit: clean make-afl
	mkdir -p out/exit-test
	$(CC) src/exit.c -o exit
	afl-$(AFL_VERSION)/afl-fuzz -i test-cases/exit-test -o out/exit-test ./exit

# WIP. Needs harnass
cpython: clean make-afl
	apt-get install python
	cd src/cpython-3.4.6 && CC=$(CC) ./configure && make

jq: clean make-afl
	cd src/jq-jq-1.5 && CC=$(CC) ./configure && make
	cd src/jq-jq-1.5 && /.$(AFL) -i /fuzz/jq/in -o /fuzz/jq/out -- /src/jq-jq-1.5/jq '.'

jqvuln: clean make-afl
	cd src/jq-jq-1.5-vuln && CC=$(CC) ./configure && make
	cd src/jq-jq-1.5-vuln && /.$(AFL) -i /fuzz/jqvuln/in -o /fuzz/jqvuln/out -- /src/jq-jq-1.5-vuln/jq '.'


bc: clean make-afl
	apt-get install -y texinfo
	cd src/bc-1.07 && CC=$(CC) ./configure && make
	cd src/bc-1.07 && /.$(AFL) -i /fuzz/bc/in -o /fuzz/bc/out -- /src/bc-1.07/bc/bc -l


# WIP. Needs harnass
R: clean make-afl
	apt-get install -y gfortran libreadline6-dev bzip2 libbz2-dev liblzma-dev libpcre3-dev libcurl4-openssl-dev
	cd src/R-3.4.0 && CC=$(CC) ./configure --with-x=no && make
	/bin/bash #cd src/R-3.4.0 && /.$(AFL) -i /fuzz/bc/in -o /fuzz/bc/out -- /src/R-3.4.0/R
